import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app//globals.css"
import {Header} from "@/components/shared";
import {SearchProvider} from "@/contexts/search-context";
import {cn} from "@/lib/utils";

export const metadata: Metadata = {
  title: "Living Hope | .lib",
  description: "Generated by create next app",
};

export default function SongPageLayout({
children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
      <main className="min-h-screen">
          <SearchProvider>
              <Header isSearchBarActive={false}/>
              {children}
          </SearchProvider>
      </main>
  );
}
