import type { Metadata } from "next";
import "../globals.css";
import {Header} from "@/components/shared";
import {SearchProvider} from "@/contexts/search-context";

export const metadata: Metadata = {
  title: "Living Hope | .lib",
  description: "Generated by create next app",
};

export default function HomePageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main className="min-h-screen antialiased">
        <SearchProvider>
          <Header isSerachBarActive={true} className="sticky top-15 z-10" />
          {children}
        </SearchProvider>
      </main>
  );
}
