import type { Metadata } from "next";
import {Geist_Mono, Lora } from "next/font/google";
import "./globals.css"



const lora = Lora({
  subsets: ["cyrillic", "latin"],
  variable: '--font-lora-one',
  weight: ["400", "500", "600", "700"]
})
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Living Hope | .lib",
  description: "Generated by create next app",
};

export default function RootLayout({ auth, children,}: Readonly<{ auth: React.ReactNode; children: React.ReactNode; }>){
  return (
    <html 
        lang="en"
        data-scroll-behavior='smooth'
        className={`antialiased`} >
      <body>
          {auth}
          {children}
      </body>
    </html>
  );
}